export const categories = [
  {
    _id: "644a6a1d1d99756b22f3f501",
    children: ["Organic Food"],
    children_slug: ["organic-food"],
    approved: "true",
    slug: "organic-food",
    status: "Show",
    parent: "Organic Food",
    type: "Grocery",
    image: "https://i.ibb.co/xmGhNRF/apple.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f503",
    children: ["Sauces", "Pickles & Condiments"],
    children_slug: ["sauces", "pickles-&-condiments"],
    approved: "true",
    slug: "sauces-&-pickles",
    status: "Show",
    parent: "Sauces & Pickles",
    type: "Grocery",
    image: "https://i.postimg.cc/mk09xvk4/chili-sauce.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f507",
    children: [
      "Cleaner",
      "Laundry",
      "Air Freshener",
      "Water Filter",
      "Pest Control",
      "Cleaning Tools",
    ],
    children_slug: [
      "cleaner",
      "laundry",
      "air-freshener",
      "water-filter",
      "pest-control",
      "cleaning-tools",
    ],
    approved: "true",
    slug: "household-tools",
    status: "Hide",
    parent: "Household Tools",
    type: "Home Accessories",
    image: "https://i.ibb.co/rdY6zL0/cleaner.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f509",
    children: ["Cat Care", "Dog Care", "Bird Care"],
    children_slug: ["cat-care", "dog-care", "bird-care"],
    approved: "true",
    slug: "pet-care",
    status: "Hide",
    parent: "Pet Care",
    type: "Grocery",
    image: "https://i.postimg.cc/RVVzrWfg/cat.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f4f9",
    children: [
      "Bath",
      "Cosmetics",
      "Oral Care",
      "Skin Care",
      "Body Care",
      "Shaving Needs",
    ],
    children_slug: [
      "bath",
      "cosmetics",
      "oral-care",
      "skin-care",
      "body-care",
      "shaving-needs",
    ],
    approved: "true",
    slug: "new-arrival",
    status: "Show",
    parent: "New Arrival",
    type: "Health Care",
    image: "https://i.postimg.cc/gjz1P7wx/beauty.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f4ff",
    children: ["Tea", "Water", "Juice", "Coffee", "Energy Drinks"],
    children_slug: ["tea", "water", "juice", "coffee", "energy-drinks"],
    approved: "true",
    slug: "drinks",
    status: "Show",
    parent: "Drinks",
    type: "Grocery",
    image: "https://i.ibb.co/Dz8LKDX/soft-drink.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f502",
    children: ["Honey"],
    children_slug: ["honey"],
    approved: "true",
    slug: "honey",
    status: "Show",
    parent: "Honey",
    type: "Grocery",
    image: "https://i.postimg.cc/65JSfy6H/honey-1.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f505",
    children: ["Chocolate", "Chips & Nuts", "Canned Food"],
    children_slug: ["chocolate", "chips-&-nuts", "canned-food"],
    approved: "true",
    slug: "snacks-&-instant",
    status: "Show",
    parent: "Snacks & Instant",
    type: "Grocery",
    image: "https://i.ibb.co/HT7c6VT/chips.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f508",
    children: ["Baby Food", "Baby Accessories"],
    children_slug: ["baby-food", "baby-accessories"],
    approved: "true",
    slug: "baby-care",
    status: "Show",
    parent: "Baby Care",
    type: "Health Care",
    image: "https://i.postimg.cc/QNqrnQBB/baby.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f50a",
    children: [
      "Bath",
      "Cosmetics",
      "Oral Care",
      "Skin Care",
      "Body Care",
      "Shaving Needs",
    ],
    children_slug: [
      "bath",
      "cosmetics",
      "oral-care",
      "skin-care",
      "body-care",
      "shaving-needs",
    ],
    approved: "true",
    slug: "beauty-&-health",
    status: "Hide",
    parent: "Beauty & Health",
    type: "Health Care",
    image: "https://i.postimg.cc/gjz1P7wx/beauty.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f50b",
    children: ["Sports", "Fitness"],
    children_slug: ["sports", "fitness"],
    approved: "true",
    slug: "sports-&-fitness",
    status: "Show",
    parent: "Sports & Fitness",
    type: "Sports & Fitness",
    image: "https://i.ibb.co/qNCvxT0/dumbbell.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f4fa",
    children: ["Fish", "Meat"],
    children_slug: ["fish", "meat"],
    approved: "true",
    slug: "fish-&-meat",
    status: "Show",
    parent: "Fish & Meat",
    type: "Grocery",
    image: "https://i.ibb.co/y0zXYj5/carp-fish.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f4fb",
    children: ["Dry Fruits", "Fresh Fruits", "Fresh Vegetable"],
    children_slug: ["dry-fruits", "fresh-fruits", "fresh-vegetable"],
    approved: "true",
    slug: "fruits-&-vegetable",
    status: "Show",
    parent: "Fruits & Vegetable",
    type: "Grocery",
    image: "https://i.postimg.cc/RZ275n3f/cabbage.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f4fe",
    children: ["Bread", "Cereal"],
    children_slug: ["bread", "cereal"],
    approved: "true",
    slug: "breakfast",
    status: "Show",
    parent: "Breakfast",
    type: "Grocery",
    image: "https://i.ibb.co/dgPzSt7/bagel.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f500",
    children: ["Dairy", "Ice Cream", "Butter & Ghee"],
    children_slug: ["dairy", "ice-cream", "butter-&-ghee"],
    approved: "true",
    slug: "milk-&-dairy",
    status: "Show",
    parent: "Milk & Dairy",
    type: "Grocery",
    image: "https://i.ibb.co/181Qpm8/milk.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f504",
    children: ["Jam & Jelly"],
    children_slug: ["jam-&-jelly"],
    approved: "true",
    slug: "jam-&-jelly",
    status: "Show",
    parent: "Jam & Jelly",
    type: "Grocery",
    image: "https://i.postimg.cc/rmLvfsMC/strawberry-jam-1.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f4fc",
    children: ["Fresh Seafood"],
    children_slug: ["fresh-seafood"],
    approved: "true",
    slug: "fresh-seafood",
    status: "Show",
    parent: "Fresh Seafood",
    type: "Grocery",
    image: "https://i.ibb.co/pfscwF4/shrimp.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f4fd",
    children: ["Oil", "Rice", "Flour", "Dry Vegetable", "Spices & Mixes"],
    children_slug: ["oil", "rice", "flour", "dry-vegetable", "spices-&-mixes"],
    approved: "true",
    slug: "cooking-essentials",
    status: "Show",
    parent: "Cooking Essentials",
    type: "Grocery",
    image: "https://i.ibb.co/hBv30Rt/frying-pan.png",
  },
  {
    _id: "644a6a1d1d99756b22f3f506",
    children: ["Cakes", "Biscuits"],
    children_slug: ["cakes", "biscuits"],
    approved: "true",
    slug: "biscuits-&-cakes",
    status: "Hide",
    parent: "Biscuits & Cakes",
    type: "Grocery",
    image: "https://i.postimg.cc/0jVF5Cmc/cookie.png",
  },
];
